### PR TITLE
update DeepOSM info

### PR DESCRIPTION
**Pull request by andrewljohnson**
- add other technical and code contributors
- changed that project doesn't focus on hiking trails

note: not sure why the last line is highlighted, that wasn't changed

### CODE REVIEW

**Comment by workergnome** [comment]
Hi there, @andrewljohnson!  Thanks for this.  

I'm fine with these changes— @golanlevin, any objections to updating their reference text?

**Comment by andrewljohnson** [comment]
nice to meet you guys, I was also a CMU student once upon a time!

**Comment by golanlevin** [comment]
All good, nice to hear from them

**Comment by workergnome** [comment]
Great!  Merged and deployed.

**Pull request merged**
